backend:
  name: git-gateway
  repo: joergmartin1969-arch/joergmartindigital
  branch: main
  site_url: https://joergmartindigital.de

media_folder: "images/ratgeber" # Ordner für Bilder umbenannt
public_folder: "/images/ratgeber"

collections:
  - name: "ratgeber"           # Interner Name (kleingeschrieben)
    label: "Ratgeber-Beiträge" # Das steht jetzt oben links im Dashboard
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Beitragsbild", name: "image", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown"}